import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import './globals.css'
import { twJoin } from 'tailwind-merge'

const sans = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={twJoin(sans.variable, 'font-sans size-full')}>{children}</body>
    </html>
  )
}
