import './globals.css'

import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import { headers } from 'next/headers'
import { twJoin } from 'tailwind-merge'

import Nav from '@/components/Nav'

const sans = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers()
  const userAgent = headersList.get('user-agent')
  const isMobile = !!userAgent?.includes('Mobile')

  return (
    <html lang="en">
      <body className={twJoin(sans.variable, 'size-full font-sans')}>
        <Nav isMobile={isMobile} />
        {children}
      </body>
    </html>
  )
}
